name: TheNewPin
version: 1.0
main: org.cesar.thenewpin.pin.Main
api-version: 1.21
commands:
  pin:
    description: Abre el menú del PIN manualmente
permissions:
  pin.use:
    description: Permite usar el sistema de PIN
    default: true
